DROP TABLE IF EXISTS TBL_SETTINGS;
CREATE TABLE TBL_SETTINGS(
    TYPE STRING NOT NULL PRIMARY KEY,
    CONTENT JSON NOT NULL
);

INSERT INTO TBL_SETTINGS (TYPE, CONTENT) VALUES ('internal', '{"mqttUrl":"localhost:1883"}');