SECRET_KEY = 'Joey'
TOKEN_SCHEME = 'JWT'
TOKEN_EXPIRE = 1800

DB_NAME = 'robot-rpi.db'
DB_INIT_SCRIPT = 'sql/schema.sql'
SETTINGS_ITEMS_INTERNAL = 'internal'
SETTINGS_ITEMS_WATSON = 'watson'
SETTINGS_ITEMS = [SETTINGS_ITEMS_INTERNAL, SETTINGS_ITEMS_WATSON]

MQTT_CLIENT_ID = 'ai-robot-car-rpi'
MQTT_WATSON_DEVICE_TYPE = 'rpi'
MQTT_WATSON_DEVICE_ID = 'car'
MQTT_WATSON_EVENT_CONTROL = 'control'
MQTT_WATSON_EVENT_HUMITURE = 'humiture'
MQTT_WATSON_TOPIC = 'iot-2/type/' + MQTT_WATSON_DEVICE_TYPE + '/id/' + MQTT_WATSON_DEVICE_ID + '/evt/{event}/fmt/json'