MSG_LOGIN_SUCCESSFUL = 'Login successful!'
MSG_LOGIN_FAILURE = 'Login failed!'
MSG_TOKEN_AUTH_FAILURE = 'Authorization failure!'
MSG_SAVE_SETTINGS_SUCCESSFUL = 'Settings saved successfully!'
MSG_SAVE_SETTINGS_FAILED = 'Settings saved failed!'
